/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkmastermind;

import java.text.SimpleDateFormat;
import java.util.Calendar;

/**
 *
 * @author Ignacio
 */
public class VentanaHistorial extends javax.swing.JDialog {

    int numPartida = 0;
    int numJugada  = 0;
    
    public VentanaHistorial(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        //Centramos la ventana
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAHistorial = new javax.swing.JTextArea();
        jBAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Historial MasterMind");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Historial:");

        jTAHistorial.setEditable(false);
        jTAHistorial.setColumns(20);
        jTAHistorial.setRows(5);
        jScrollPane1.setViewportView(jTAHistorial);

        jBAceptar.setText("Aceptar");
        jBAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBAceptar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBAceptar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptarActionPerformed
        //Salimos de la Ventan Modal
        this.dispose();
    }//GEN-LAST:event_jBAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaHistorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaHistorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaHistorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaHistorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaHistorial dialog = new VentanaHistorial(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    public void limpiarHistorial(){
        jTAHistorial.setText("");
    }
    public void iniciarPartida(int nivel){
        numPartida++;
        if (nivel != 0){
            jTAHistorial.setText("PARTIDA "+numPartida + " - NIVEL " + nivel + " - HORA: " + obtenerTiempo() + "\n");
            jTAHistorial.append("------------------------------------------------------\n");
        }
        else{
            jTAHistorial.setText("PARTIDA "+numPartida + " - NIVEL MANUAL - HORA: " + obtenerTiempo() + "\n");
            jTAHistorial.append("---------------------------------------------------------------\n");
        }
        numJugada = 0;
    }
    public void incluirNuevaJugada(int combinacion[], int longitud, int verdes, int blancas){
        numJugada++;
        jTAHistorial.append("Combinacion " + numJugada); 
        jTAHistorial.append(": " + obtenerCombinacion(combinacion, longitud));
        jTAHistorial.append(": " + verdes + " correctas, " + blancas + " mal colocadas");
        jTAHistorial.append("\n");
    }
    private String obtenerCombinacion(int combinacion[], int longitud){

        String auxCombi = "";

        //Generamos una Cadena con la Cobinación
        for (int x=0; x<longitud; x++){
            if (x!=0)
                auxCombi+= ", " + combinacion[x];                
            else
                auxCombi = "[" + combinacion[x];
        }
        //Retornamos la Combinacion en una Cadena
        return auxCombi + "]";
    }
    public void ganoPartida(String tiempo, int puntuacion){
        jTAHistorial.append("--------------------------------------------------\n");
        jTAHistorial.append("!!GANÓ LA PARTIDA EN " + numJugada + " INTENTOS!!\n");
        jTAHistorial.append("Puntuacion: " + puntuacion + "\n");
        jTAHistorial.append("Tiempo empleado: " + tiempo);
    }
    public void perdioPartida(String tiempo){
        jTAHistorial.append("--------------------------------------------------\n");
        jTAHistorial.append("!!OHHHH, PERDIO LA PARTIDA\n");
        jTAHistorial.append("Puntuacion: 0\n");
        jTAHistorial.append("Tiempo empleado: " + tiempo);
    }
    private String obtenerTiempo(){
        Calendar rightNow = Calendar.getInstance();
        SimpleDateFormat horaActual = new SimpleDateFormat("HH:mm:ss");
        return horaActual.format(rightNow.getTime());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTAHistorial;
    // End of variables declaration//GEN-END:variables
}
